name: Deploy to Gist
on:
  push:
    branches: [master]  
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1.0.4
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 827426cab7f7424c408aed1497ba5517
          gist_file_name: Arch-Linux-Tips-And-Tricks.md
          file_path: README.md
