name: Deploy to Gist
on:
  push:
    branches: [master]  
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1.0.4
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: ${{ vars.GIST_ID }}
          gist_file_name: ${{ vars.GIST_FILE_NAME }}
          file_path: ${{ vars.FILE_PATH }}
